[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
roots = ["svelte.config.js"]
language-servers = ["tailwindcss-ls", "svelteserver"]

[[language]]
name = "python"
language-servers = [ "pyright" ]

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["Gopkg.toml", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = [ "gopls" ]
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.mdpls]
command = "/usr/bin/mdpls"
config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }

[[language]]
name = "markdown"
language-servers = ["marksman", "mdpls"]
